/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description Courses with their health scores.
         *
         *     The score is recomputed per course rather than stored, so it always
         *     reflects the current graph. With a handful of courses this is fast
         *     enough; a larger deployment would cache it.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_code}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Gaps */
        get: operations["course_gaps_api_courses__course_code__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skill Prerequisites
         * @description The dependency chain behind a skill.
         *
         *     This is what turns "you are missing X" into "here is what X costs",
         *     and it is the clearest demonstration of why the ontology is a graph.
         */
        get: operations["skill_prerequisites_api_skills__skill__prerequisites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_code}/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Roadmap
         * @description A teaching sequence, ordered by prerequisite dependency.
         *
         *     The gap report says what is missing. This says what to do about it and in
         *     what order, because some gaps cannot be taught until others are in place.
         *     Nothing here is course-specific: the sequence comes from the graph, so an
         *     uploaded syllabus is treated exactly like a seeded one.
         */
        get: operations["course_roadmap_api_courses__course_code__roadmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_code}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Evidence
         * @description The job postings a course's audit was measured against.
         *
         *     Every figure in the gap report reduces to a count of postings. Listing
         *     them turns that count from an assertion into something the reader can
         *     check, which matters most where the count is low enough to withhold the
         *     findings entirely.
         */
        get: operations["course_evidence_api_courses__course_code__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/augment/{course_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Augment Course
         * @description Propose modifications for a course. This is the third mandated component.
         */
        post: operations["augment_course_api_augment__course_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description Skills ranked by market demand, flagged by whether they are taught.
         *
         *     Returns skill nodes and their prerequisite edges rather than every node
         *     in the database: a force-directed layout of the full graph is visually
         *     unreadable, and the demand ranking is what carries meaning.
         *
         *     The bound on `limit` is enforced here rather than left to Cypher. A
         *     negative value reached Neo4j and came back as a raw 500, which is what a
         *     judge editing the URL would have seen. FastAPI now rejects it with a 422
         *     that names the constraint.
         */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_market_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Corpus-level numbers, so the dashboard can state its own evidence base.
         */
        get: operations["summary_api_market_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Programme Report
         * @description The whole-degree view.
         *
         *     Gaps here are skills no course teaches, which is a stronger claim than a
         *     per-course gap and the one a dean actually acts on.
         */
        get: operations["programme_report_api_programme_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programme/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coverage
         * @description Which skills the programme teaches, and in how many courses.
         *
         *     A skill taught in one course is a single point of failure; one taught in
         *     six may be redundant. Both are worth knowing before revising anything.
         */
        get: operations["coverage_api_programme_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programme/defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Defects
         * @description Skills taught without their prerequisites anywhere in the programme.
         *
         *     This is a structural defect rather than a market gap: students are being
         *     asked to absorb material they have no foundation for, which is precisely
         *     what an accreditation review looks for.
         */
        get: operations["defects_api_programme_defects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programme/placement/{skill}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Placement
         * @description Which course should teach a given skill, and what it would cost.
         */
        get: operations["placement_api_programme_placement__skill__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programme/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit History
         * @description Every audit taken, and the drift between the two most recent.
         */
        get: operations["audit_history_api_programme_audit_get"];
        put?: never;
        /**
         * Run Audit
         * @description Record what the market demands right now, and report any drift.
         *
         *     A single audit cannot show drift, so the response says so explicitly
         *     rather than fabricating a trend from one data point.
         */
        post: operations["run_audit_api_programme_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accreditation/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Co Po Matrix
         * @description Course Outcome to Programme Outcome correlations.
         *
         *     Pass `course` for a single course, or omit it for the whole programme.
         *     Every cell carries the skill and confidence it was derived from, so an
         *     assessor can audit any claim rather than taking the number on trust.
         *
         *     An unknown course is rejected rather than answered with an empty matrix.
         *     This is a compliance document: a report that looks valid but describes a
         *     course that does not exist is worse than an error, because somebody
         *     could file it.
         */
        get: operations["co_po_matrix_api_accreditation_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accreditation/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Findings
         * @description What an assessor would flag.
         *
         *     Ordered by how seriously an NBA panel treats them: an uncovered
         *     Programme Outcome is a major non-conformity, one resting on a single
         *     course is a risk, and thin coverage is an observation.
         */
        get: operations["findings_api_accreditation_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accreditation/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Programme Outcomes
         * @description The twelve NBA Programme Outcomes, for reference.
         */
        get: operations["programme_outcomes_api_accreditation_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/syllabi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Syllabus */
        post: operations["upload_syllabus_api_syllabi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus a quick view of whether the graph is populated.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AugmentProposal
         * @description Stage 6 output: modifications a professor can adopt without a redesign.
         */
        AugmentProposal: {
            /** Course Code */
            course_code: string;
            /** Added Outcomes */
            added_outcomes: string[];
            /** Case Studies */
            case_studies: string[];
            /** Toolsets */
            toolsets: string[];
            /** Project Prompts */
            project_prompts: string[];
            /** Rationale */
            rationale: string;
        };
        /** Body_upload_syllabus_api_syllabi_post */
        Body_upload_syllabus_api_syllabi_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * GapReport
         * @description Stage 5 output.
         *
         *     `health_score` is the share of market demand *within this course's own
         *     subject area* that the syllabus covers, not a share of the whole tech
         *     market. A single course covers only three to twelve percent of total
         *     market demand, which is normal, so scoring against the whole market
         *     produced numbers that were arithmetically right and completely
         *     misleading.
         *
         *     `scored_against` names the subject areas used as the denominator, so the
         *     number can be interpreted rather than taken on faith.
         *
         *     `domain_postings` is how many postings in the corpus actually demand a
         *     skill in that subject area. It is the denominator behind the denominator,
         *     and it has to be reported: a civil engineering course compared against
         *     three civil postings and one compared against three hundred produce
         *     identically confident-looking output otherwise. When it falls below
         *     `EVIDENCE_FLOOR` the report is marked `evidence_thin`, and the ranked
         *     gaps below are demand from adjacent fields rather than this course's own.
         */
        GapReport: {
            /** Course Code */
            course_code: string;
            /** Course Title */
            course_title: string;
            /** Health Score */
            health_score?: number | null;
            /** Scored Against */
            scored_against?: string[];
            /**
             * Domain Postings
             * @default 0
             */
            domain_postings: number;
            /**
             * Evidence Thin
             * @default false
             */
            evidence_thin: boolean;
            /** Evidence Note */
            evidence_note?: string | null;
            /** Gaps */
            gaps: components["schemas"]["SkillGap"][];
        };
        /**
         * GapSeverity
         * @enum {string}
         */
        GapSeverity: "critical" | "high" | "moderate" | "low";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SkillGap
         * @description One missing or under-covered skill, with the evidence supporting it.
         */
        SkillGap: {
            /** Canonical Skill */
            canonical_skill: string;
            /**
             * Category
             * @default general
             */
            category: string;
            severity: components["schemas"]["GapSeverity"];
            /** Market Demand */
            market_demand: number;
            /** Curriculum Coverage */
            curriculum_coverage: number;
            /** Prerequisite Distance */
            prerequisite_distance: number;
            /** Trend Slope */
            trend_slope?: number | null;
            /** Postings Requiring */
            postings_requiring: number;
            /** Postings Total */
            postings_total: number;
            /** Evidence */
            evidence: string;
        };
        /**
         * SkillTrend
         * @description Slope is None until the forecaster ships. The contract never changes.
         */
        SkillTrend: {
            /** Canonical Skill */
            canonical_skill: string;
            /** History */
            history: components["schemas"]["TrendPoint"][];
            /** Slope */
            slope?: number | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Period */
            period: string;
            /** Frequency */
            frequency: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    course_gaps_api_courses__course_code__gaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skill_prerequisites_api_skills__skill__prerequisites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_roadmap_api_courses__course_code__roadmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_evidence_api_courses__course_code__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    augment_course_api_augment__course_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AugmentProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: {
                /** @description How many demand-ranked skills to include. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_market_trends_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTrend"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_market_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    programme_report_api_programme_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_api_programme_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    defects_api_programme_defects_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    placement_api_programme_placement__skill__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_history_api_programme_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    run_audit_api_programme_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    co_po_matrix_api_accreditation_matrix_get: {
        parameters: {
            query?: {
                course?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_accreditation_findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    programme_outcomes_api_accreditation_outcomes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    upload_syllabus_api_syllabi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_syllabus_api_syllabi_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
