/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description Courses with their health scores.
         *
         *     The score is recomputed per course rather than stored, so it always
         *     reflects the current graph. With a handful of courses this is fast
         *     enough; a larger deployment would cache it.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_code}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course Gaps */
        get: operations["course_gaps_api_courses__course_code__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skill Prerequisites
         * @description The dependency chain behind a skill.
         *
         *     This is what turns "you are missing X" into "here is what X costs",
         *     and it is the clearest demonstration of why the ontology is a graph.
         */
        get: operations["skill_prerequisites_api_skills__skill__prerequisites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/augment/{course_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Augment Course
         * @description Propose modifications for a course. This is the third mandated component.
         */
        post: operations["augment_course_api_augment__course_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Graph
         * @description Skills ranked by market demand, flagged by whether they are taught.
         *
         *     Returns skill nodes and their prerequisite edges rather than every node
         *     in the database: a force-directed layout of the full graph is visually
         *     unreadable, and the demand ranking is what carries meaning.
         */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends */
        get: operations["trends_api_market_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description Corpus-level numbers, so the dashboard can state its own evidence base.
         */
        get: operations["summary_api_market_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/syllabi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Syllabus */
        post: operations["upload_syllabus_api_syllabi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus a quick view of whether the graph is populated.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AugmentProposal
         * @description Stage 6 output: modifications a professor can adopt without a redesign.
         */
        AugmentProposal: {
            /** Course Code */
            course_code: string;
            /** Added Outcomes */
            added_outcomes: string[];
            /** Case Studies */
            case_studies: string[];
            /** Toolsets */
            toolsets: string[];
            /** Project Prompts */
            project_prompts: string[];
            /** Rationale */
            rationale: string;
        };
        /** Body_upload_syllabus_api_syllabi_post */
        Body_upload_syllabus_api_syllabi_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * GapReport
         * @description Stage 5 output.
         *
         *     `health_score` is the share of market demand *within this course's own
         *     subject area* that the syllabus covers, not a share of the whole tech
         *     market. A single course covers only three to twelve percent of total
         *     market demand, which is normal, so scoring against the whole market
         *     produced numbers that were arithmetically right and completely
         *     misleading.
         *
         *     `scored_against` names the subject areas used as the denominator, so the
         *     number can be interpreted rather than taken on faith.
         */
        GapReport: {
            /** Course Code */
            course_code: string;
            /** Course Title */
            course_title: string;
            /** Health Score */
            health_score: number;
            /** Scored Against */
            scored_against?: string[];
            /** Gaps */
            gaps: components["schemas"]["SkillGap"][];
        };
        /**
         * GapSeverity
         * @enum {string}
         */
        GapSeverity: "critical" | "high" | "moderate" | "low";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SkillGap
         * @description One missing or under-covered skill, with the evidence supporting it.
         */
        SkillGap: {
            /** Canonical Skill */
            canonical_skill: string;
            /**
             * Category
             * @default general
             */
            category: string;
            severity: components["schemas"]["GapSeverity"];
            /** Market Demand */
            market_demand: number;
            /** Curriculum Coverage */
            curriculum_coverage: number;
            /** Prerequisite Distance */
            prerequisite_distance: number;
            /** Trend Slope */
            trend_slope?: number | null;
            /** Postings Requiring */
            postings_requiring: number;
            /** Postings Total */
            postings_total: number;
            /** Evidence */
            evidence: string;
        };
        /**
         * SkillTrend
         * @description Slope is None until the forecaster ships. The contract never changes.
         */
        SkillTrend: {
            /** Canonical Skill */
            canonical_skill: string;
            /** History */
            history: components["schemas"]["TrendPoint"][];
            /** Slope */
            slope?: number | null;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Period */
            period: string;
            /** Frequency */
            frequency: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    course_gaps_api_courses__course_code__gaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skill_prerequisites_api_skills__skill__prerequisites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    augment_course_api_augment__course_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AugmentProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_market_trends_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTrend"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_market_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    upload_syllabus_api_syllabi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_syllabus_api_syllabi_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
